version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: source/conf.py

formats:
  - pdf
